name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        run: |
          version=`echo ${{ github.ref_name }} | sed -e "s/^v//"`
          docker buildx build --platform linux/386 -t nmgsz/docker-laravel8-runtime:${version} -t nmgsz/docker-laravel8-runtime:latest . --push
          docker buildx build --platform linux/amd64 -t nmgsz/docker-laravel8-runtime:${version} -t nmgsz/docker-laravel8-runtime:latest . --push
          docker buildx build --platform linux/arm/v6 -t nmgsz/docker-laravel8-runtime:${version} -t nmgsz/docker-laravel8-runtime:latest . --push
          docker buildx build --platform linux/arm/v7 -t nmgsz/docker-laravel8-runtime:${version} -t nmgsz/docker-laravel8-runtime:latest . --push
          docker buildx build --platform linux/arm64/v8 -t nmgsz/docker-laravel8-runtime:${version} -t nmgsz/docker-laravel8-runtime:latest . --push
          docker buildx build --platform linux/ppc64le -t nmgsz/docker-laravel8-runtime:${version} -t nmgsz/docker-laravel8-runtime:latest . --push
          docker buildx build --platform linux/s390x -t nmgsz/docker-laravel8-runtime:${version} -t nmgsz/docker-laravel8-runtime:latest . --push
          docker image ls
